import requests
import os
import resend
from datetime import datetime
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
NEWS_API_KEY = os.getenv("NEWS_API_KEY")
FROM_EMAIL = os.getenv("FROM_EMAIL")

client = OpenAI(api_key=OPENAI_API_KEY)
resend.api_key = RESEND_API_KEY


def validate_env():
    required = [
        "OPENAI_API_KEY",
        "NEWS_API_KEY",
        "RESEND_API_KEY",
        "FROM_EMAIL",
    ]
    missing = [name for name in required if not os.getenv(name)]
    if missing:
        raise ValueError(
            "Missing required environment variables: " + ", ".join(missing)
        )


def fetch_ai_news():
    url = (
        "https://newsapi.org/v2/everything"
        f"?q=artificial+intelligence&sortBy=publishedAt&apiKey={NEWS_API_KEY}"
    )

    try:
        response = requests.get(url, timeout=20)
        response.raise_for_status()
    except requests.RequestException:
        return None

    articles = response.json().get("articles", [])[:7]
    if not articles:
        return None

    headlines = "\n\n".join(
        [
            f"Title: {a['title']}\nDescription: {a['description']}"
            for a in articles
            if a["title"] and a["description"]
        ]
    )
    return headlines if headlines else None


def generate_summary(news_content):
    prompt = f"""
You are my personal AI intelligent assistant.
Below are today's latest news about artificial intelligence.

{news_content}

Tasks:
1. Sumarize the 5 most important developments in the news.
2. Explain why they matter and how they could impact the future of AI.
3. Provide a concise summary of the overall state of AI based on
    these news articles.
4. End with one fun, slightly absurd automation idea that could be
    implemented for my personal/professional use.

Format nicely for an email newsletter And sign from Aarons Assistant.
    """
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1000,
    )
    return response.choices[0].message.content


def send_email(content):
    today = datetime.now().strftime("%Y-%m-%d")

    resend.Emails.send(
        {
            "from": FROM_EMAIL,
            "to": FROM_EMAIL,
            "subject": f"Daily AI News Summary - {today}",
            "html": f"""
<div style="font-family: Arial, sans-serif; line-height: 1.5; color: #333;">
    <h2>Good Morning!</h2>
    <p>{content.replace('\n', '<br>')}</p>
    <hr>
    <small>Generated by your AI assistant. Stay curious!</small>
</div>
        """,
        }
    )


def main():
    validate_env()

    print("Fetching AI news...")
    news_content = fetch_ai_news()
    if not news_content:
        print("No AI news could be fetched right now. Exiting.")
        return

    print("Generating summary...")
    summary = generate_summary(news_content)

    print("Sending email...")
    send_email(summary)
    print("Done!")


if __name__ == "__main__":
    main()
